version: '3.1'
services:
  nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    links:
      - web
      - backend
      - tileserver

  web:
    build: 
      context: ../

  tile-server:
    build:
      context: tile-server/
    command: ["-p", "8080",  "-c", "/data/tileserver-config.json", "--verbose"]
    volumes:
      - tile-data:/data

  backend:
    image: oevgk18/backend
    volumes:
      - ./generator-results/:/backend/data

  tile-converter:
    build:
      context: tile-converter/
    volumes:
      - ./generator-results:/generator-results
      - tile-data:/tile-data

volumes:
  tile-data: