version: '3.1'
services:
  nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    links:
      - web
      - backend
      - tileserver

  web:
    build: 
      context: ../

  tileserver:
    image: klokantech/tileserver-gl
    command: ["-p", "8080",  "-c", "tileserver-config.json", "--verbose"]
    volumes:
      - ./oevgk18-data:/data

  backend:
    image: oevgk18/backend
    volumes:
      - ./oevgk18-data:/backend/data